version: 2

version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - make -C docs prep
    post_build:
      - python3 -m build
      - mkdir -p _jl/files
      - cp -a dist/factoriocalc-*.whl _jl/
      - python3 docs/demo-prep.py
      - cd _jl && jupyter lite build
         --output-dir="$READTHEDOCS_OUTPUT/html/demo"

sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/build-environment.yml

#python:
#  install:
#    - requirements: docs/requirements.txt


